apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 64bb5f4e50c25191765f731e0eca4507a280a5a0
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/juan-carnicero-end-to-end
  labels:
    app.kubernetes.io/instance: end-to-end-assignment
    app.kubernetes.io/name: end-to-end-assignment
  name: end-to-end-assignment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: end-to-end-assignment
    app.kubernetes.io/instance: end-to-end-assignment
    app.kubernetes.io/name: end-to-end-assignment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 64bb5f4e50c25191765f731e0eca4507a280a5a0
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/juan-carnicero-end-to-end
  labels:
    app: end-to-end-assignment
    app.kubernetes.io/instance: end-to-end-assignment
    app.kubernetes.io/name: end-to-end-assignment
  name: end-to-end-assignment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: end-to-end-assignment
      app.kubernetes.io/instance: end-to-end-assignment
      app.kubernetes.io/name: end-to-end-assignment
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 64bb5f4e50c25191765f731e0eca4507a280a5a0
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/juan-carnicero-end-to-end
      labels:
        app: end-to-end-assignment
        app.kubernetes.io/instance: end-to-end-assignment
        app.kubernetes.io/name: end-to-end-assignment
    spec:
      containers:
      - image: quay.io/jm_carnicero/end-to-end-assignment:64bb5f4e50c25191765f731e0eca4507a280a5a0
        name: nextjs
        ports:
        - containerPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 64bb5f4e50c25191765f731e0eca4507a280a5a0
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/juan-carnicero-end-to-end
  labels:
    app.kubernetes.io/instance: end-to-end-assignment
    app.kubernetes.io/name: end-to-end-assignment
  name: end-to-end-assignment
spec:
  to:
    kind: Service
    name: end-to-end-assignment
