apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: webhook-receiver
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: end-to-end-assignment-
    spec:
      params:
      - name: app-name
        value: "end-to-end-assignment"
      - name: source-repo
        value: "https://github.com/cloud-native-garage-method-cohort/juan-carnicero-end-to-end"
      - name: image-repo
        value: "quay.io/jm_carnicero/end-to-end-assignment"
      pipelineRef:
        name: end-to-end-assignment
      serviceAccountName: build-robot
      workspaces:
      - name: pipeline-shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce 
            resources:
              requests:
                storage: 1Gi
      - name: manifest-target-repo
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce 
            resources:
              requests:
                storage: 1Gi
      - name: git-credentials
        secret:
          secretName: git-credentials

